"""
Course and module definitions for Laser Safety LMS.
PDF paths are relative to the project root (same directory as laser_lms_app.py).
"""

COURSES = [
    {
        "id": "course-1",
        "title": "Laser Safety Fundamentals",
        "description": "Master the core principles of laser safety including hazard classification, control measures, and the role of the Laser Safety Officer.",
        "category": "Fundamentals",
        "difficulty": "Beginner",
        "icon": "🔴",
        "color": "#dc2626",
        "total_minutes": 75,
        "modules": [
            {
                "id": "c1-m1",
                "title": "Introduction to Laser Hazards",
                "description": "Overview of laser technology and the fundamental hazards associated with laser use in entertainment and industrial settings.",
                "pdf_path": "laser-safety-lms/public/docs/course-1-fundamentals/intro-laser-hazards.pdf",
                "key_takeaways": [
                    "Lasers emit coherent, monochromatic light that can cause severe eye and skin injuries",
                    "The primary hazard is ocular damage — retinal burns can be permanent",
                    "Non-beam hazards include electrical, chemical, and fire risks",
                    "Understanding hazard distance (NOHD) is essential for safe operations",
                ],
                "minutes": 15,
            },
            {
                "id": "c1-m2",
                "title": "Laser Classification System",
                "description": "Understanding Class 1 through Class 4 laser classifications and what each means for safety requirements.",
                "pdf_path": "laser-safety-lms/public/docs/course-1-fundamentals/laser-classification.pdf",
                "key_takeaways": [
                    "Class 1: Safe under all normal conditions — inherently safe or fully enclosed",
                    "Class 2: Low power visible lasers — blink reflex provides adequate protection",
                    "Class 3R/3B: Medium power — direct viewing hazardous without controls",
                    "Class 4: High power — hazardous to eye and skin, diffuse reflections dangerous",
                ],
                "minutes": 15,
            },
            {
                "id": "c1-m3",
                "title": "Role of the Laser Safety Officer",
                "description": "Responsibilities, authority, and training requirements for a designated Laser Safety Officer (LSO).",
                "pdf_path": "laser-safety-lms/public/docs/course-1-fundamentals/lso-role.pdf",
                "key_takeaways": [
                    "The LSO is responsible for overseeing the laser safety program",
                    "LSO must have authority to halt unsafe operations immediately",
                    "LSO duties include hazard evaluation, control implementation, and personnel training",
                    "ANSI Z136.1 defines LSO qualifications and responsibilities",
                ],
                "minutes": 15,
            },
            {
                "id": "c1-m4",
                "title": "Beam Hazard Calculations",
                "description": "How to calculate Nominal Ocular Hazard Distance (NOHD) and Maximum Permissible Exposure (MPE) values.",
                "pdf_path": "laser-safety-lms/public/docs/course-1-fundamentals/beam-hazard-calculations.pdf",
                "key_takeaways": [
                    "MPE is the maximum laser exposure level considered safe for the eye or skin",
                    "NOHD is the distance at which irradiance falls below the MPE",
                    "Calculations depend on wavelength, pulse duration, beam divergence, and power",
                    "Always calculate for worst-case scenario (e.g., dilated pupil in darkness)",
                ],
                "minutes": 15,
            },
            {
                "id": "c1-m5",
                "title": "Engineering & Administrative Controls",
                "description": "Practical implementation of laser safety controls: barriers, interlocks, PPE, and standard operating procedures.",
                "pdf_path": "laser-safety-lms/public/docs/course-1-fundamentals/safety-controls.pdf",
                "key_takeaways": [
                    "Engineering controls (enclosures, interlocks) are preferred over administrative controls",
                    "Laser Controlled Areas must be clearly posted with warning signs",
                    "Personal Protective Equipment (OD-rated eyewear) is the last line of defense",
                    "Written SOPs must be developed and followed for all Class 3B/4 operations",
                ],
                "minutes": 15,
            },
        ],
    },
    {
        "id": "course-2",
        "title": "FDA Compliance & Reporting",
        "description": "Navigate FDA electronic product radiation regulations, variance applications, and mandatory incident reporting for laser products.",
        "category": "Regulatory",
        "difficulty": "Intermediate",
        "icon": "🏛️",
        "color": "#2563eb",
        "total_minutes": 90,
        "modules": [
            {
                "id": "c2-m1",
                "title": "FDA Regulatory Framework",
                "description": "Overview of 21 CFR 1040 — the federal standard governing laser product performance.",
                "pdf_path": "laser-safety-lms/public/docs/course-2-fda-compliance/fda-regulatory-framework.pdf",
                "key_takeaways": [
                    "21 CFR 1040 sets performance standards for electronic laser products",
                    "Manufacturers must certify products before sale in the US",
                    "The FDA Center for Devices and Radiological Health (CDRH) enforces these standards",
                    "Both domestic manufacturers and importers must comply",
                ],
                "minutes": 15,
            },
            {
                "id": "c2-m2",
                "title": "Variance Applications",
                "description": "When and how to apply for a variance from FDA performance standards for entertainment laser use.",
                "pdf_path": "laser-safety-lms/public/docs/course-2-fda-compliance/variance-applications.pdf",
                "key_takeaways": [
                    "A variance is required to operate Class IIIb/IV lasers for entertainment purposes",
                    "Variance applications must include show descriptions, safety measures, and operator qualifications",
                    "FDA may impose conditions on variances — all must be strictly followed",
                    "Variances are granted to specific operators for specific show types",
                ],
                "minutes": 15,
            },
            {
                "id": "c2-m3",
                "title": "Laser Notice 50 Requirements",
                "description": "Understanding Laser Notice 50 and required audience scanning restrictions.",
                "pdf_path": "laser-safety-lms/public/docs/course-2-fda-compliance/laser-notice-50.pdf",
                "key_takeaways": [
                    "Laser Notice 50 (LN50) provides guidance on audience scanning with Class IIIb/IV lasers",
                    "Beam irradiance in audience areas must remain below MPE levels",
                    "LN50 establishes minimum distances and beam characteristics for audience exposure",
                    "Operators must calculate and document compliance with LN50 criteria",
                ],
                "minutes": 15,
            },
            {
                "id": "c2-m4",
                "title": "Mandatory Incident Reporting",
                "description": "Legal requirements for reporting laser-related injuries and accidents to the FDA.",
                "pdf_path": "laser-safety-lms/public/docs/course-2-fda-compliance/incident-reporting.pdf",
                "key_takeaways": [
                    "Manufacturers must report product defects that could cause injury within 30 days",
                    "Reports are submitted via MedWatch or manufacturer reporting systems",
                    "Failure to report is a federal violation with significant penalties",
                    "Operators should document all incidents and near-misses internally",
                ],
                "minutes": 15,
            },
            {
                "id": "c2-m5",
                "title": "FDA Forms & Documentation",
                "description": "Completing FDA Form 3632 and other required compliance documents.",
                "pdf_path": "laser-safety-lms/public/docs/course-2-fda-compliance/fda-forms.pdf",
                "key_takeaways": [
                    "FDA Form 3632 is used by manufacturers to report product introductions",
                    "Annual reporting of laser product sales/distribution may be required",
                    "Documentation must be retained for a minimum period specified by regulations",
                    "Electronic submissions are now preferred by CDRH",
                ],
                "minutes": 15,
            },
            {
                "id": "c2-m6",
                "title": "State vs. Federal Jurisdiction",
                "description": "How FDA federal regulations interact with state-level laser regulations.",
                "pdf_path": "laser-safety-lms/public/docs/course-2-fda-compliance/state-federal-jurisdiction.pdf",
                "key_takeaways": [
                    "FDA sets minimum federal standards; states may impose stricter requirements",
                    "Some states require separate permits in addition to FDA variances",
                    "Federal law preempts conflicting state law in product standards",
                    "Operators must comply with both federal and applicable state regulations",
                ],
                "minutes": 15,
            },
        ],
    },
    {
        "id": "course-3",
        "title": "Biological Hazards & Classification",
        "description": "Understand how laser radiation interacts with human tissue, IEC 60825 international standards, and biological safety thresholds.",
        "category": "Safety Science",
        "difficulty": "Advanced",
        "icon": "🧬",
        "color": "#16a34a",
        "total_minutes": 75,
        "modules": [
            {
                "id": "c3-m1",
                "title": "Ocular Hazards & Anatomy",
                "description": "How different laser wavelengths affect different parts of the eye.",
                "pdf_path": "laser-safety-lms/public/docs/course-3-bio-hazards/ocular-hazards.pdf",
                "key_takeaways": [
                    "The retina is the most vulnerable ocular structure for visible and near-IR wavelengths",
                    "UV lasers (200-400nm) primarily damage the cornea and lens",
                    "Far-IR lasers (>1400nm) are absorbed by water in the cornea and vitreous",
                    "Retinal damage is often painless and permanent",
                ],
                "minutes": 15,
            },
            {
                "id": "c3-m2",
                "title": "Skin Hazards & Thermal Effects",
                "description": "Laser-induced skin injuries including burns, photochemical effects, and threshold calculations.",
                "pdf_path": "laser-safety-lms/public/docs/course-3-bio-hazards/skin-hazards.pdf",
                "key_takeaways": [
                    "Skin absorbs laser energy differently depending on wavelength and pigmentation",
                    "Thermal injury occurs when tissue temperature exceeds 45°C for extended periods",
                    "UV exposure can cause photochemical reactions — including carcinogenic effects",
                    "High-power lasers can cause immediate burns; lower powers cause delayed photochemical damage",
                ],
                "minutes": 15,
            },
            {
                "id": "c3-m3",
                "title": "IEC 60825-1 Standard",
                "description": "The international laser product safety standard — classification, labeling, and manufacturer requirements.",
                "pdf_path": "laser-safety-lms/public/docs/course-3-bio-hazards/iec-60825-1.pdf",
                "key_takeaways": [
                    "IEC 60825-1 is the primary international standard for laser product safety",
                    "Defines accessible emission limits (AEL) for each laser class",
                    "Manufacturers must classify products and apply appropriate warning labels",
                    "IEC classification differs slightly from FDA/ANSI — Class 3R vs Class IIIa",
                ],
                "minutes": 15,
            },
            {
                "id": "c3-m4",
                "title": "Maximum Permissible Exposure Tables",
                "description": "Using MPE tables for eye and skin across all wavelengths and pulse durations.",
                "pdf_path": "laser-safety-lms/public/docs/course-3-bio-hazards/mpe-tables.pdf",
                "key_takeaways": [
                    "MPE values vary by wavelength (nm), exposure duration (seconds), and beam area",
                    "For pulsed lasers, both single-pulse and repetitive-pulse MPEs must be evaluated",
                    "Eye MPEs are significantly lower than skin MPEs for the same conditions",
                    "ANSI Z136.1 Table 5a/5b provides comprehensive MPE values",
                ],
                "minutes": 15,
            },
            {
                "id": "c3-m5",
                "title": "Protective Eyewear Selection",
                "description": "Optical density requirements, wavelength coverage, and proper selection of laser safety eyewear.",
                "pdf_path": "laser-safety-lms/public/docs/course-3-bio-hazards/protective-eyewear.pdf",
                "key_takeaways": [
                    "Optical Density (OD) measures how much laser radiation the eyewear attenuates",
                    "Required OD = log10(beam irradiance / MPE)",
                    "Eyewear must be rated for the specific laser wavelength(s) in use",
                    "Damage to eyewear (scratches, discoloration) reduces its protective value",
                ],
                "minutes": 15,
            },
        ],
    },
    {
        "id": "course-4",
        "title": "US State & Local Regulations",
        "description": "State-by-state guide to laser entertainment regulations, permit requirements, and contacts for 10 major states.",
        "category": "Regulatory",
        "difficulty": "Intermediate",
        "icon": "🗺️",
        "color": "#7c3aed",
        "total_minutes": 100,
        "modules": [
            {"id": "c4-m1",  "title": "California", "description": "CDPH laser permits, local fire marshal requirements.", "pdf_path": "laser-safety-lms/public/docs/course-4-state-regs/california.pdf", "key_takeaways": ["CDPH requires registration of Class IIIb/IV lasers", "Local fire marshal approval required for entertainment shows", "Stricter audience exposure limits in some areas", "Liability insurance and training documentation required"], "minutes": 10},
            {"id": "c4-m2",  "title": "Florida",    "description": "Florida DOH radiation control program requirements.", "pdf_path": "laser-safety-lms/public/docs/course-4-state-regs/florida.pdf",    "key_takeaways": ["Laser registration certificate required", "Advance notification to Florida DOH for entertainment shows", "Strict MPE compliance at audience scanning distances", "Designated LSO required on-site during performances"], "minutes": 10},
            {"id": "c4-m3",  "title": "New York",   "description": "NY State DOH and NYC-specific permit requirements.", "pdf_path": "laser-safety-lms/public/docs/course-4-state-regs/new-york.pdf",   "key_takeaways": ["Registration of facilities using Class 3B/4 lasers required", "NYC has additional requirements beyond state regulations", "Safety plans must be submitted to NYC Fire Department", "State inspections possible for high-profile shows"], "minutes": 10},
            {"id": "c4-m4",  "title": "Texas",      "description": "Texas DSHS laser safety requirements.", "pdf_path": "laser-safety-lms/public/docs/course-4-state-regs/texas.pdf",      "key_takeaways": ["Registration required for Class IIIb/IV in professional use", "Comply with both state and local ordinances", "Follows federal FDA variance requirements", "State radiation control program applies"], "minutes": 10},
            {"id": "c4-m5",  "title": "Nevada",     "description": "Nevada regulations — critical for Las Vegas operations.", "pdf_path": "laser-safety-lms/public/docs/course-4-state-regs/nevada.pdf",     "key_takeaways": ["Specific regulations for the Las Vegas entertainment market", "Clark County has additional requirements for casino shows", "Permanent installations require more extensive permitting", "Coordinates closely with FDA for high-profile variance shows"], "minutes": 10},
            {"id": "c4-m6",  "title": "Illinois",   "description": "Illinois IEMA radiation safety requirements.", "pdf_path": "laser-safety-lms/public/docs/course-4-state-regs/illinois.pdf",   "key_takeaways": ["IEMA administers radiation protection program", "Registration fees and renewal requirements apply", "Chicago has additional municipal requirements", "Document all Class 3B/4 laser use activities"], "minutes": 10},
            {"id": "c4-m7",  "title": "Georgia",    "description": "Georgia DNR environmental radiation control.", "pdf_path": "laser-safety-lms/public/docs/course-4-state-regs/georgia.pdf",    "key_takeaways": ["Georgia EPD regulates lasers under radiation program", "Commercial Class IIIb/IV lasers require registration", "Atlanta has significant entertainment venue concentration", "Follows federal MPE guidelines with state administrative requirements"], "minutes": 10},
            {"id": "c4-m8",  "title": "Washington", "description": "Washington State DOH radiation protection requirements.", "pdf_path": "laser-safety-lms/public/docs/course-4-state-regs/washington.pdf", "key_takeaways": ["Registration of Class 3B/4 facilities required", "Seattle entertainment district concentration of laser venues", "Safety training documentation required", "Participates in CRCPD standards program"], "minutes": 10},
            {"id": "c4-m9",  "title": "Massachusetts", "description": "Massachusetts DPH — one of the most comprehensive state programs.", "pdf_path": "laser-safety-lms/public/docs/course-4-state-regs/massachusetts.pdf", "key_takeaways": ["Laser Radiation Safety Permit required for all Class 3B/4 uses", "Detailed safety plans including beam diagrams required", "Active inspections and enforcement capability", "Submit detailed safety plans to MDPH"], "minutes": 10},
            {"id": "c4-m10", "title": "Colorado",   "description": "Colorado CDPHE radiation control requirements.", "pdf_path": "laser-safety-lms/public/docs/course-4-state-regs/colorado.pdf",   "key_takeaways": ["Radiation Management Program governs laser use", "Registration required for professional Class 3B/4 use", "High-altitude venues affect atmospheric absorption calculations", "Follows CRCPD suggested regulations as baseline"], "minutes": 10},
        ],
    },
    {
        "id": "course-5",
        "title": "International Regulations",
        "description": "Global laser safety standards — EU directives, UK regulations, Canadian requirements, and international harmonization.",
        "category": "Regulatory",
        "difficulty": "Advanced",
        "icon": "🌍",
        "color": "#0891b2",
        "total_minutes": 90,
        "modules": [
            {"id": "c5-m1", "title": "EU Laser Safety Directives",    "description": "EU directives governing laser products and worker exposure.", "pdf_path": "laser-safety-lms/public/docs/course-5-international/eu-directives.pdf",         "key_takeaways": ["EU 2006/25/EC governs worker exposure to artificial optical radiation", "CE marking requires compliance with applicable EU directives", "EN 60825 is the European adoption of IEC 60825", "Member states may implement additional national requirements"], "minutes": 15},
            {"id": "c5-m2", "title": "UK Post-Brexit Regulations",    "description": "UK-specific requirements following Brexit divergence.", "pdf_path": "laser-safety-lms/public/docs/course-5-international/uk-regulations.pdf",         "key_takeaways": ["UKCA marking replaces CE marking for UK domestic market", "HSE guidance on laser safety at work applies", "UK retained EU OAR directive equivalent in domestic law", "Entertainment shows require local authority safety assessment"], "minutes": 15},
            {"id": "c5-m3", "title": "Canadian Laser Regulations",    "description": "Health Canada Radiation Emitting Devices Act requirements.", "pdf_path": "laser-safety-lms/public/docs/course-5-international/canada-regulations.pdf",    "key_takeaways": ["Health Canada regulates under Radiation Emitting Devices Act (REDA)", "Canadian standards align closely with ANSI Z136 series", "Provincial OHS acts apply to laser workplaces", "Contact provincial regulators for show permits"], "minutes": 15},
            {"id": "c5-m4", "title": "Australia & New Zealand",       "description": "AS/NZS 2211 standards and Radiation Council requirements.", "pdf_path": "laser-safety-lms/public/docs/course-5-international/australia-nz.pdf",         "key_takeaways": ["AS/NZS 2211 adopts IEC 60825 with Australasian modifications", "Each state/territory has radiation protection legislation", "Registration with state radiation control authorities required", "New Zealand Radiation Safety Act governs laser use"], "minutes": 15},
            {"id": "c5-m5", "title": "International Show Documentation", "description": "Documentation packages for international deployments.", "pdf_path": "laser-safety-lms/public/docs/course-5-international/international-show-docs.pdf", "key_takeaways": ["Compliance docs may need local language translation", "Equipment export may require destination country compliance", "Temporary import procedures vary by country", "Hire local safety consultants for jurisdiction-specific requirements"], "minutes": 15},
            {"id": "c5-m6", "title": "IEC & ISO Harmonization",       "description": "How international standards bodies harmonize global requirements.", "pdf_path": "laser-safety-lms/public/docs/course-5-international/iec-iso-harmonization.pdf", "key_takeaways": ["IEC TC76 is responsible for laser safety standards", "IEC 60825-1 Ed. 3 (2014) is the current international baseline", "ISO 11553 covers laser safety for processing machines", "Harmonization reduces trade barriers but national deviations still exist"], "minutes": 15},
        ],
    },
    {
        "id": "course-6",
        "title": "Outdoor Laser Safety & Airspace",
        "description": "FAA regulations, aviation laser safety, outdoor hazard assessment, and atmospheric considerations.",
        "category": "Operations",
        "difficulty": "Intermediate",
        "icon": "✈️",
        "color": "#0284c7",
        "total_minutes": 75,
        "modules": [
            {"id": "c6-m1", "title": "FAA Laser Regulations Overview", "description": "FAA regulations on laser illumination of aircraft.", "pdf_path": "laser-safety-lms/public/docs/course-6-outdoor-airspace/faa-regulations.pdf",          "key_takeaways": ["FAA Order 7400.2 governs laser operations near navigable airspace", "Pointing a laser at an aircraft is a federal crime under 18 USC 39A", "FAA defines Critical Flight Zones (CFZ) and Laser Free Zones (LFZ)", "Coordinate with FAA air traffic control before outdoor shows"], "minutes": 15},
            {"id": "c6-m2", "title": "NOTAM Procedures",               "description": "How to file Notices to Air Missions for outdoor shows.", "pdf_path": "laser-safety-lms/public/docs/course-6-outdoor-airspace/notam-procedures.pdf",         "key_takeaways": ["NOTAM must be filed 24-72 hours before outdoor laser operations", "NOTAMs notify pilots of temporary hazards or airspace restrictions", "FAA Laser NOTAM format requires specific beam characteristic information", "Coordinate with local ARTCC for complex airspace"], "minutes": 15},
            {"id": "c6-m3", "title": "Outdoor Hazard Calculations",    "description": "Calculating laser hazard distances in outdoor environments.", "pdf_path": "laser-safety-lms/public/docs/course-6-outdoor-airspace/outdoor-hazard-calculations.pdf", "key_takeaways": ["Outdoor NOHD must account for atmospheric transmission losses", "Beam quality degrades over long distances due to atmospheric turbulence", "Weather conditions affect hazard distances", "Extended NOHD (ENOHD) used for uncontrolled outdoor environments"], "minutes": 15},
            {"id": "c6-m4", "title": "Securing Outdoor Laser Shows",   "description": "Site assessment, perimeter security, and beam termination strategies.", "pdf_path": "laser-safety-lms/public/docs/course-6-outdoor-airspace/securing-outdoor-shows.pdf", "key_takeaways": ["Identify all potential beam interception points before the show", "Use beam stops or terminators when beams approach restricted zones", "Establish a laser-controlled area with physical barriers", "Coordinate with venue security and local law enforcement"], "minutes": 15},
            {"id": "c6-m5", "title": "International Outdoor Standards", "description": "IEC 60825-3 and international standards for laser displays.", "pdf_path": "laser-safety-lms/public/docs/course-6-outdoor-airspace/international-outdoor-standards.pdf", "key_takeaways": ["IEC 60825-3 Ed. 2 specifically addresses safety of laser displays", "Distinguishes between laser light show (audience present) and laser display", "Provides detailed guidance on audience scanning safety criteria", "European countries increasingly enforce IEC 60825-3"], "minutes": 15},
        ],
    },
    {
        "id": "course-7",
        "title": "Event Safety & Operations",
        "description": "Event safety management including crowd dynamics, weather protocols, venue assessment, and emergency procedures.",
        "category": "Operations",
        "difficulty": "Intermediate",
        "icon": "🎪",
        "color": "#d97706",
        "total_minutes": 90,
        "modules": [
            {"id": "c7-m1", "title": "Event Safety Planning",      "description": "Pre-event safety planning frameworks and stakeholder coordination.", "pdf_path": "laser-safety-lms/public/docs/course-7-event-safety/event-safety-planning.pdf", "key_takeaways": ["Safety planning must begin months before the event", "Event Safety Plans should address all hazards: laser, crowd, weather, electrical", "Coordinate with venue management, promoters, and emergency services", "Define clear chain of command for safety decisions"], "minutes": 15},
            {"id": "c7-m2", "title": "Crowd Safety & Dynamics",    "description": "Crowd behavior, density limits, and managing audience safety.", "pdf_path": "laser-safety-lms/public/docs/course-7-event-safety/crowd-safety.pdf",         "key_takeaways": ["Crowd density above 4 persons/m² creates significant crush risk", "Festival-mode audiences move unpredictably — plan beam scanning accordingly", "Establish clear evacuation routes and communicate them to audience", "Staff-to-audience ratio affects ability to respond to safety incidents"], "minutes": 15},
            {"id": "c7-m3", "title": "Weather Protocols",          "description": "Weather monitoring, decision thresholds, and evacuation protocols.", "pdf_path": "laser-safety-lms/public/docs/course-7-event-safety/weather-protocols.pdf",   "key_takeaways": ["Lightning within 10 miles = suspend outdoor operations immediately", "Wind speeds above 25mph affect laser beam stability and audience safety", "Rain and fog significantly reduce laser hazard distances", "Develop written weather response plans with specific trigger thresholds"], "minutes": 15},
            {"id": "c7-m4", "title": "Venue Assessment Checklist", "description": "Systematic approach to evaluating venues for laser show safety.", "pdf_path": "laser-safety-lms/public/docs/course-7-event-safety/venue-assessment.pdf",   "key_takeaways": ["Document all reflective surfaces that could redirect laser beams", "Identify HVAC ducts, fire suppression systems, and overhead hazards", "Map power infrastructure and establish dedicated circuits for laser equipment", "Assess audience sight lines and identify potential unintended exposure zones"], "minutes": 15},
            {"id": "c7-m5", "title": "Emergency Response",         "description": "Laser injury response, shutdown procedures, and incident documentation.", "pdf_path": "laser-safety-lms/public/docs/course-7-event-safety/emergency-response.pdf", "key_takeaways": ["For laser eye injury: do NOT rub eye, cover with sterile dressing, seek immediate medical care", "Maintain Emergency Stop (E-Stop) accessible to LSO at all times", "Document all incidents with date, time, witnesses, and circumstances", "Post-incident review must occur before resuming operations"], "minutes": 15},
            {"id": "c7-m6", "title": "Insurance & Liability",      "description": "Insurance requirements, liability management, and contractual risk allocation.", "pdf_path": "laser-safety-lms/public/docs/course-7-event-safety/insurance-liability.pdf", "key_takeaways": ["General liability minimum $1M per occurrence for professional operations", "Errors & Omissions insurance protects against professional negligence claims", "Venue agreements should specify indemnification responsibilities clearly", "Maintain detailed records of safety procedures as evidence of due diligence"], "minutes": 15},
        ],
    },
    {
        "id": "course-8",
        "title": "Entertainment Technology Standards",
        "description": "ANSI/ESTA standards for entertainment technology including laser-specific performance standards.",
        "category": "Standards",
        "difficulty": "Advanced",
        "icon": "📋",
        "color": "#be185d",
        "total_minutes": 75,
        "modules": [
            {"id": "c8-m1", "title": "ANSI Z136 Laser Safety Standards",         "description": "The complete ANSI Z136 series — the authoritative US laser safety standard.", "pdf_path": "laser-safety-lms/public/docs/course-8-standards/ansi-z136.pdf",                   "key_takeaways": ["ANSI Z136.1 is the general laser safety standard covering all laser uses", "Z136.2 addresses safe use of optical fiber communication systems", "Z136.3 covers laser use in health care settings", "Z136.8 covers research and development environments"], "minutes": 15},
            {"id": "c8-m2", "title": "ESTA Entertainment Standards",              "description": "Entertainment Services and Technology Association standards.", "pdf_path": "laser-safety-lms/public/docs/course-8-standards/esta-standards.pdf",                  "key_takeaways": ["ESTA E1.46 covers laser safety in entertainment applications", "ESTA standards developed through ANSI-accredited consensus process", "E1.46 provides guidance for audience scanning and operator qualifications", "ESTA maintains Technical Standards Program with ongoing development"], "minutes": 15},
            {"id": "c8-m3", "title": "ANSI E1.46 Entertainment Laser Standard",  "description": "Deep dive into ANSI E1.46 — the entertainment-specific laser standard.", "pdf_path": "laser-safety-lms/public/docs/course-8-standards/ansi-e146.pdf",                   "key_takeaways": ["E1.46 requires show operators to hold appropriate safety training certifications", "Standard defines minimum distances for audience scanning", "Addresses both enclosed venue and outdoor show requirements", "Compliance increasingly required by venues and insurers"], "minutes": 15},
            {"id": "c8-m4", "title": "Electrical Safety Standards",               "description": "IEC 60950, UL 60950, and electrical safety standards for laser systems.", "pdf_path": "laser-safety-lms/public/docs/course-8-standards/electrical-safety-standards.pdf", "key_takeaways": ["Laser power supplies must meet applicable electrical safety standards", "NFPA 70 (NEC) governs electrical installations in the US", "Temporary power for events has specific requirements under NFPA 70", "Equipment must be properly grounded and protected from moisture"], "minutes": 15},
            {"id": "c8-m5", "title": "Standards Compliance Documentation",        "description": "How to document standards compliance for clients and authorities.", "pdf_path": "laser-safety-lms/public/docs/course-8-standards/compliance-documentation.pdf",       "key_takeaways": ["Maintain a Standards Compliance Matrix listing all applicable standards", "Document deviations from standards with risk assessments and mitigations", "Third-party certification provides independent verification", "Compliance documentation should be updated when standards are revised"], "minutes": 15},
        ],
    },
]

COURSE_MAP = {c["id"]: c for c in COURSES}

def get_course(course_id: str) -> dict:
    return COURSE_MAP.get(course_id, {})

def get_module(course_id: str, module_id: str) -> dict:
    course = get_course(course_id)
    for m in course.get("modules", []):
        if m["id"] == module_id:
            return m
    return {}
